# Generated by Django 3.2.25 on 2024-07-07 09:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField()),
                ('offer_percentage', models.DecimalField(decimal_places=2, help_text='Percentage discount offered by the coupon.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount required to use the coupon.', max_digits=10)),
                ('maximum_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Maximum order amount required to use the coupon.', max_digits=10)),
                ('overall_usage_limit', models.PositiveIntegerField(default=0, help_text='Total number of times the coupon can be used.')),
                ('limit_per_user', models.PositiveIntegerField(default=1, help_text='Maximum number of times a single user can use the coupon.')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Total number of times the coupon has been used.')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
