# Generated by Django 3.2.25 on 2024-07-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_delete_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='is_active',
        ),
    ]
