# Generated by Django 3.2.25 on 2024-07-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
